version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: kruger_gateway
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: